extensions:
  opamp:
    server:
      http:
        endpoint: http://localhost:4321/v1/opamp
        polling_interval: 5s

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

exporters:
  otlp_http:
    endpoint: http://3.89.63.91:9090/api/v1/otlp

service:
  extensions: [opamp]
  pipelines:
    metrics:
      receivers: [otlp]
      exporters: [otlp_http]
